server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}

scrape_configs:
  - job_name: golang-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: golang-app
          __path__: /app/logs/request.log
